# Generated by Django 5.2.1 on 2025-09-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bands/'),
        ),
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bands/logos/'),
        ),
        migrations.AddField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
